spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/agendamento
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  application:
    name: Sistema de Reservas API
  