spring:
  application:
    name: Sistema de Reservas API
  datasource:
    url: jdbc:h2:mem:reservas
    username : sa
    password: 1234
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
